# Once you have finished making changes, use the "rebuild mathfly"
# command to enact them.
"numbers_max" = 500
"pronunciation" = "Core"
"capitals_prefix" = "big"
# Square brackets mean that a word is optional:
# the command will work with or without it
# for example, "numb ten" and "ten" both do the same thing.
"numbers_prefix" = "[numb]"
"dictation_prefix" = "say"
# "right wally" will produce an "end" keypress
"extreme" = "wally"

# NATO phonetic alphabet
[letters]
"alpha" = "a"
"bravo" = "b"
"charlie" = "c"
"delta" = "d"
"echo" = "e"
"foxtrot" = "f"
"golf" = "g"
"hotel" = "h"
"india" = "i"
"juliet" = "j"
"kilo" = "k"
"lima" = "l"
"mike" = "m"
"november" = "n"
"oscar" = "o"
"papa" = "p"
"quebec" = "q"
"romeo" = "r"
"sierra" = "s"
"tango" = "t"
"uniform" = "u"
"victor" = "v"
"whiskey" = "w"
"x-ray" = "x"
"yankee" = "y"
"zulu" = "z"

# My own phonetic alphabet, based on that of Talon.
# Single syllables speed things up a bit, potentially
# at the cost of accuracy, enable "alternative_letters"
# in settings.toml to use these instead of NATO
[letters_alt]
"(anti | arch)" = "a"
"bat" = "b"
"cap" = "c"
"die" = "d"
"each" = "e"
"fail" = "f"
"(gone | gust)" = "g"
"(harp | harm)" = "h"
"sit" = "i"
"jury" = "j"
"crunch" = "k"
"look" = "l"
"(made | mad)" = "m"
"near" = "n"
"odd" = "o"
"pit" = "p"
"queer" = "q"
"red" = "r"
"sun" = "s"
"trap" = "t"
"urge" = "u"
"vest" = "v"
"whale" = "w"
"box" = "x"
"yes" =  "y"
"zulu" = "z"

# (command1 | command2) means that either command
# will do the same thing
[punctuation]
"ampersand" = "ampersand"
"apostrophe" = "apostrophe"
"(asterisk | starling)" = "asterisk"
"at sign" = "at"
"backslash" = "backslash"
"backtick" = "backtick"
"pipe symbol" = "bar"
"caret" = "caret"
"colon" = "colon"
"comma" = "comma"
"boom" = "comma, space"
"dollar" = "dollar"
"(dot | point)" = "dot"
"(quote | quotes)" = "dquote"
"equals" = "equal"
"exclamation" = "exclamation"
"hashtag" = "hash"
"hyphen" = "hyphen"
"minus" = "minus"
"percent" = "percent"
"plus" = "plus"
"question mark" = "question"
"semicolon" = "semicolon"
"slash" = "slash"
"single quote" = "squote"
"tilde" = "tilde"
"underscore" = "underscore"
"greater than" = "rangle"
"less than" = "langle"
"brax" = "lbracket, rbracket, left"
"prekris" = "lparen, rparen, left"
"curly" = "lbrace, rbrace, left"

# These can be followed by a number to execute multiple times
[repeatable_keys]
"(space | ace)" = "space"
"(tab | tabby)" = "tab"
"(enter | shock)" = "enter"
"(backspace | clear)" = "backspace"
"splat" = "c-backspace"
"(delete | deli)" = "del"
"(escape | eskimo)" = "escape"
"(duple | duplicate)" = "home, s-end, c-c, right, enter, c-v"

# these cannot
[non_repeatable_keys]
"shackle" = "home, s-end"
"(copy | stoosh)" = "c-c"
"(paste | spark)" = "c-v"
"cut" = "c-x"
"home" = "home"
"end" = "end"
"save" = "c-s"

# these require a pause before activation, in order to reduce
# unwanted recognition of destructive commands
[noCCR_repeatable_keys]
"undo" = "c-z"
"redo" = "c-y"

[noCCR_non_repeatable_keys]

[directions]
"left" = "left"
"right" = "right"
"up" = "up"
"down" = "down"

[directions_alt]
"lease" = "left"
"ross" = "right"
"sauce" = "up"
"dunce" = "down"

# for example, "queue left two" executes ctrl-shift-left twice,
# selecting two words to the left.
[modifiers]
"queue" = "cs-"
"shin" = "s-"
"fly" = "c-"