"numbers_max" = 500
"capitals_prefix" = "big"

[letters]
"alpha" = "a"
"bravo" = "b"
"charlie" = "c"
"delta" = "d"
"echo" = "e"
"foxtrot" = "f"
"golf" = "g"
"hotel" = "h"
"india" = "i"
"juliett" = "j"
"kilo" = "k"
"lima" = "l"
"mike" = "m"
"november" = "n"
"oscar" = "o"
"papa" = "p"
"quebec" = "q"
"romeo" = "r"
"sierra" = "s"
"tango" = "t"
"uniform" = "u"
"victor" = "v"
"whiskey" = "w"
"x-ray" = "x"
"yankee" = "y"
"zulu" = "z"

[letters_alt]
"(anti | arch)" = "a"
"bat" = "b"
"cap" = "c"
"die" = "d"
"each" = "e"
"fail" = "f"
"(gone | gust)" = "g"
"(harp | harm)" = "h"
"sit" = "i"
"jury" = "j"
"crunch" = "k"
"look" = "l"
"(made | mad)" = "m"
"near" = "n"
"odd" = "o"
"pit" = "p"
"queer" = "q"
"red" = "r"
"sun" = "s"
"trap" = "t"
"urge" = "u"
"vest" = "v"
"whale" = "w"
"box" = "x"
"yes" =  "y"
"zulu" = "z"


[punctuation]
"ampersand" = "ampersand"
"apostrophe" = "apostrophe"
"(asterisk | starling)" = "asterisk"
"at sign" = "at"
"backslash" = "backslash"
"backtick" = "backtick"
"pipe symbol" = "bar"
"caret" = "caret"
"colon" = "colon"
"comma" = "comma"
"dollar" = "dollar"
"(dot | point)" = "dot"
"(quote | quotes)" = "dquote"
"equals" = "equal"
"(escape | eskimo)" = "escape"
"exclamation" = "exclamation"
"hashtag" = "hash"
"hyphen" = "hyphen"
"minus" = "minus"
"percent" = "percent"
"plus" = "plus"
"question" = "question"
"semicolon" = "semicolon"
"slash" = "slash"
"single quote" = "squote"
"tilde" = "tilde"
"underscore" = "underscore"
"greater than" = "rangle"
"less than" = "langle"

[keys]
"(space | ace)" = "space"
"(tab | tabby)" = "tab"
"(enter | shock)" = "enter"
"(backspace | clear)" = "backspace"
"(delete | deli)" = "del"

[misc_core_keys]
"shackle" = "home, s-end"
"(copy | stoosh)" = "c-c"
"(paste | spark)" = "c-v"
"cut" = "c-x"
"(duple | duplicate)" = "home, s-end, c-c, right, enter, c-v"
"home" = "home"
"end" = "end"
"save" = "c-s"

[directions]
"left" = "left"
"left wally" = "home"
"right" = "right"
"right wally" = "end"
"up" = "up"
"up wally" = "c-home"
"down" = "down"
"down wally" = "c-end"


[directions_alt]
"lease" = "left"
"lease wally" = "home"
"ross" = "right"
"ross wally" = "end"
"sauce" = "up"
"sauce wally" = "c-home"
"dunce" = "down"
"dunce wally" = "c-end"

[modifiers]
"queue" = "cs-"
"shin" = "s-"
"fly" = "c-"