"greek_prefix" = "greek"
"symbol1_prefix" = ""
"symbol2_prefix" = "symbol"

[greek_letters]
"alpha" = "alpha"
"beater" = "beta"
"gamma" = "gamma"
"delta" = "delta"
"epsilon" = "epsilon"
"zita" = "zeta"
"eater" = "eta"
"theta" = "theta"
"iota" = "iota"
"kappa" = "kappa"
"lambda" = "lambda"
"mu" = "mu"
"new" = "nu"
"zee" = "xi"
"pie" = "pi"
"row" = "rho"
"sigma" = "sigma"
"tau" = "tau"
"upsilon" = "upsilon"
"phi" = "phi"
"chi" = "chi"
"sigh" = "psi"
"omega" = "omega"


[tex_symbols1]
# operators
"root" = "sqrt"
"generic root" = "root"
"integral" = "int"
"double integral" = "iint"
"triple integral" = "iiint"
"times" = "times"
"divide" = "div"
"intersection" = "cap"
"union" = "cup"
"stop" = "cdot"
"product" = "prod"
"(direct sum | oh plus)" = "oplus"
"(large direct sum | large oh plus)" = "bigoplus"
"plus or minus" = "pm"
"partial" = "partial"
# fractions and related things in the lyx fractions menu
"(nice frack | nice fraction)" = "nicefrac"
"unit" = "unitone"
"unit two" = "unittwo"
"unit fraction " = "unitfrac"
"text fraction" = "tfrac"
"display fraction" = "dfrac"
"continued fraction" = "cfrac"
"continued fraction (left)" = "cfracleft"
"continued fraction (right)" = "cfracright"
"binomial" = "binom"
"text binomial" = "tbinom"
"display binomial" = "dbinom"
# functions
"arc cosine" = "arccos"
"arc sine" = "arcsin"
"arc tan" = "arctan"
"argument" = "arg"
"beemod" = "bmod"  ## i'm not familiar with this one
"cosine" = "cos"
"hyperbolic cosine" = "cosh"
"hyperbolic cotangent" = "coth"
"cosecant" = "csc"
"degree" = "deg"
"determinant" = "det"
"dimension" = "dim"
"exponential" = "exp"
"GCD" = "gcd"
"cat hom" = "hom"
"infimum" = "inf"
"kernel" = "ker"
"liminf" = "liminf"
"natural log" = "ln"
"logarithm" = "log"
"maximum" = "max"
"minimum" = "min"
"secant" = "sec"
"sine" = "sin"
"hyperbolic sine" = "sinh"
"supremum" = "sup"
"tangent" = "tan"
"cotangent" = "cot"
"hyperbolic tangentThis" = "tanh"
"probability" = "Pr"
# misc
"infinity" = "infty"
"dot dot dot" = "dots"
"member" = "in"
"[is] not equal [to]" = "neq"
"greater [than] [or] equal [to]" = "geq"
"less [than] [or] equal [to]" = "leq"
#
"label above" = "backslash, o, v, e, r, s, e, t, space"
"label below" = "backslash, u, n, d, e, r, s, e, t, space"

[tex_symbols2]
# relations
"subset" = "subset" 
"superset" = "supset"
"strict subset" = "subsetneq"
"strict superset" = "supsetneq"
"preck" = "prec"
"preck equals" = "preceq"
"suck" = "succ"
"suck equals" = "succeq"
"approximate" = "approx"
"proportional" = "propto"
# logic
"(land|logic and)" = "land" 
"logic or" = "lor"
"primer" = "prime"
"logic not" = "lnot" 
"for all" = "forall"
"there exists" = "exists" 
# math fonts
"(beebee|blackboard bold)" = "mathbb"
"roman" = "mathrm"
"bold" = "mathbf"
"bold symbol" = "boldsymbol"
"sans serif" = "mathsf"
"italic" = "mathit"
"typewriter" = "matttt"
"blackboard" = "mathbb"
"fraktur" = "mathfrak"
"calligraphic" = "mathcal"
"formal script" = "mathscr"
"normal text mode" = "textrm"
#
"left arrow" = "leftarrow"
"right arrow" = "rightarrow"
"up arrow" = "uparrow"
"down arrow" = "downarrow"
"left right arrow" = "leftrightarrow"

[misc_lyx_keys]
"math mode" = "c-m"
"new line" = "escape:10, end, enter, c-m"
"fraction" = "a-m, f"
"super [script]" = "caret"
"sub [script]" = "underscore"
"squared" = "caret, 2, right"
"inverse" = "caret, minus, 1, right"
"(parens | prekris)" = "a-m, lparen"
"(brax | square brackets)" = "a-m, lbracket"
"(curly | curly brackets)" = "a-m, lbrace"
"absolute" = "a-m, bar"
"prime" = "apostrophe"
"summation" = "backslash, o, v, e, r, s, e, t, space, backslash, u, n, d, e, r, s, e, t, space, backslash, s, u, m, space, down"
"limit" = "backslash, u, n, d, e, r, s, e, t, space, backslash, l, i, m, space, down"
#
"accent hat" = "a-m, h"
"accent tilde" = "a-m, ampersand"
"accent dot" = "a-m, dot"
"accent double dot" = "a-m, dquote"
"accent bar" = "a-m, minus"

[misc_lyx_text]
"lyx test" = "test successful"