"greek_prefix" = "greek"
"symbol_prefix" = ""

[greek_letters]
"alpha" = "a"
"beater" = "b"
"gamma" = "g"
"delta" = "d"
"epsilon" = "e"
"zita" = "z"
"eater" = "h"
"theta" = "y"
"iota" = "i"
"kappa" = "k"
"lambda" = "l"
"mu" = "m"
"new" = "n"
"zee" = "x"
"pie" = "p"
"row" = "r"
"sigma" = "s"
"tau" = "t"
"upsilon" = "u"
"phi" = "f"
"chi" = "q"
"sigh" = "c"
"omega" = "w"

[tex_symbols]
"plus or minus" = "pm"
"times" = "times"
"divide" = "div"
"intersection" = "cap"
"union" = "cup"
"stop" = "cdot"
"approximate" = "approx"
"proportional" = "propto"
"not equal" = "neq"
"member" = "in"
"for all" = "forall"
"partial" = "partial"
"infinity" = "infty"
"dots" = "dots"
"left arrow" = "leftarrow"
"right arrow" = "rightarrow"
"up arrow" = "uparrow"
"down arrow" = "downarrow"
#
"greater [than] [or] equal [to]" = "geq"
"less [than] [or] equal [to]" = "leq"


[misc_sn_keys]
"toggle math" = "c-m"
"toggle text" = "c-t"
#
"accent hat" = "c-caret"
"accent tilde" = "c-tilde"
"accent dot" = "c-dot"
"accent double dot" = "c-dquote"
"accent bar" = "c-underscore"
#
"probability" = "P, c-0"
"absolute" = "bar, bar, left"
"inverse" = "c-h, minus, 1, right"
"chi squared" = "c-g, q, c-h, 2, right"
"fraction" = "c-f"
"(radical | root)" = "c-r"
"super [script]" = "c-h"
"sub [script]" = "c-l"
"integral" = "c-i"
"summation" = "c-7"
"squared" = "c-h, 2, right"
"prime" = "apostrophe"
"(parens | prekris)" = "c-0"
"(squares | brax)" = "c-6"
#
"label above" = "f10, i, down:11, enter/25, a, enter"
"label below" = "f10, i, down:11, enter/25, b, enter"

[misc_sn_text]
"(log natural | natural log)" = "ln"
"logarithm" = "log"
"limit" = "lim"
"sine" = "sin"
"cosine" = "cos"
"tangent" = "tan"
"secant" = "sec"
"cosecant" = "csc"
"cotangent" = "cot"