# Once you have finished making changes, use the "rebuild mathfly"
# command to enact them.
"pronunciation" = "Scientific notebook"
"greek_prefix" = "greek"
"symbol_prefix" = ""
"accent_prefix" = "accent"

[greek_letters]
"alpha" = "a"
"beater" = "b"
"gamma" = "g"
"delta" = "d"
"epsilon" = "e"
"zita" = "z"
"eater" = "h"
"theta" = "y"
"iota" = "i"
"kappa" = "k"
"lambda" = "l"
"mu" = "m"
"new" = "n"
"zee" = "x"
"pie" = "p"
"row" = "r"
"sigma" = "s"
"tau" = "t"
"upsilon" = "u"
"phi" = "f"
"chi" = "q"
"sigh" = "c"
"omega" = "w"

[misc_sn_keys]
"fraction" = "c-f"
"over" = "cs-left, c-f"
"(super [script] | to the power)" = "c-h"
"sub [script]" = "c-l"
"squared" = "c-h, 2, right"
"cubed" = "c-h, 3, right"
"inverse" = "c-h, minus, 1, right"
"(parens | parentheses)" = "c-0"
"square brackets" = "c-6"
"curly brackets" = "c-lbrace"
"absolute" = "bar, bar, left"
"chi squared" = "c-g, q, c-h, 2, right"
"(root | square root)" = "c-r"
"summation" = "c-7"
"prime" = "apostrophe"
#
"label above" = "f10, i, down:11, enter/25, a, enter"
"label below" = "f10, i, down:11, enter/25, b, enter"
#
"degrees" = "c-h, ctrl:down, c, i, r, c, ctrl:up, right"

[tex_symbols]
# operators
"integral" = "int"
"double integral" = "iint"
"triple integral" = "iiint"
"times" = "times"
"divide" = "div"
"stop" = "cdot"
"plus or minus" = "pm"
"partial" = "partial"
"infinity" = "infty"
# trig
"sine" = "sin"
"cosine" = "cos"
"tangent" = "tan"
"secant" = "sec"
"cosecant" = "csc"
"cotangent" = "cot"
"arc sine" = "arcsin"
"arc cosine" = "arccos"
"arc tan" = "arctan"
"hyperbolic sine" = "sinh"
"hyperbolic cosine" = "cosh"
"hyperbolic cotangent" = "coth"
"hyperbolic tangent" = "tanh"
# functions
"argument" = "arg"
"degree" = "deg"
"determinant" = "det"
"dimension" = "dim"
"exponential" = "exp"
"(natural (log | logarithm) | log natural)" = "ln"
"logarithm" = "log"
"maximum" = "max"
"minimum" = "min"
"product" = "prod"
"limit" = "lim"
"infimum" = "inf"
"supremum" = "sup"
"probability" = "Pr"
# relations
"there exists" = "exists"
"member" = "in"
"for all" = "forall"
"[is] not equal [to]" = "neq"
"[is] greater [than] [or] equal [to]" = "geq"
"[is] less [than] [or] equal [to]" = "leq"
"[is] approximately [equal] [to]" = "approx"
"proportional [to]" = "propto"
"preference less [than]" = "prec"
"preference less equal" = "preceq"
"preference greater [than]" = "succ"
"preference greater equal" = "succeq"
# sets
"subset" = "subset"
"superset" = "supset"
"strict subset" = "subsetneq"
"strict superset" = "supsetneq"
"intersection" = "cap"
"union" = "cup"
# logic
"logic and" = "land"
"logic or" = "lor"
"logic not" = "lnot"
#
"dot dot dot" = "dots"
"left arrow" = "leftarrow"
"right arrow" = "rightarrow"
"up arrow" = "uparrow"
"down arrow" = "downarrow"
"left right arrow" = "leftrightarrow"
"maps to" = "mapsto"
"oh plus" = "oplus"
"oh times" = "otimes"
"big oh plus" = "bigoplus"
"big oh times" = "bigotimes"
#
"diagonal dots" = "ddots"
"horizontal dots" = "cdots"
"vertical dots" = "vdots"

[misc_sn_text]
"miscellaneous test" = "miscellaneous"

[accents]
"hat" = "c-caret"
"tilde" = "c-tilde"
"dot" = "c-dot"
"double dot" = "c-dquote"
"bar" = "c-underscore"
"arrow" = "c-minus"

[denominators]
"(half | halves)" = 2
"(third | thirds)" = 3
"(quarter | quarters | fourth | fourths)" = 4
"(fifth | fifths)" = 5
"(sixth | sixths)" = 6
"(seventh | sevenths)" = 7
"(eighth | eighths)" = 8
"(ninth | ninths)" = 9
"(tenth | tenths)" = 10