ccr_path = "config/ccr.toml"
dragon_path = "C:/Program Files (x86)/Nuance/NaturallySpeaking15/Program/natspeak.exe"
editor_path = "C:/Windows/notepad.exe"
# editor_path = "C:/Program Files/Sublime Text 3/sublime_text.exe"
ccr_modules = ["core", "sn_mathematics", "lyx_mathematics", "latex", "alias"]
max_ccr_repetitions = 16
alternative_letters = false
alternative_directions = false