ccr_path = "config/ccr.toml"
dragon_path = "C:/Program Files (x86)/Nuance/NaturallySpeaking15/Program/natspeak.exe"
editor_path = "C:/Program Files/Windows NT/Accessories/wordpad.exe"
# editor_path = "C:/Program Files/Sublime Text 3/sublime_text.exe"
ccr_modules = ["core",
				"sn_mathematics",
				"lyx_mathematics",
				"latex",
				"latex_maths",
				"alias"
				]
app_modules = ["sublime",
				"lyx",
				"scientific_notebook",
				"sumatrapdf"
				]
max_ccr_repetitions = 16
alternative_letters = true
alternative_directions = true